# Generated by Django 2.0.3 on 2018-04-03 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('start_detail', models.CharField(max_length=100)),
                ('end_detail', models.CharField(max_length=100)),
                ('volume', models.FloatField()),
                ('mass', models.FloatField()),
                ('image1', models.ImageField(null=True, upload_to='cargo/')),
                ('image2', models.ImageField(null=True, upload_to='cargo/')),
                ('payment_type', models.IntegerField()),
                ('accept_person', models.CharField(max_length=100)),
                ('accept_person_contact', models.CharField(max_length=20)),
                ('shipping_date', models.DateField()),
                ('shipping_time', models.TimeField()),
                ('price', models.IntegerField()),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='info.City')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to=settings.AUTH_USER_MODEL)),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='info.City')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
