# Generated by Django 2.0.3 on 2018-04-03 17:11

import apps.client.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
        ('client', '0003_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.Transport'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Order', validators=[apps.client.models.status_test]),
        ),
        migrations.AddField(
            model_name='offer',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.Transport'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('transport', 'order')},
        ),
    ]
