# Generated by Django 2.0.3 on 2018-04-03 14:58

import apps.user.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.manager.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='raring_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='raring_sum',
            field=models.IntegerField(default=0),
        ),
    ]
