# Generated by Django 2.0.3 on 2018-04-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180403_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
